apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: datamasterr/k8s-demo-users
        env:
          - name: AUTH_ADDRESS # users-app.js의 환경변수
            value: localhost # pod 내 컨테이너간 통신
      - name: auth
        image: datamasterr/k8s-demo-auth