apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
      - name: story
        image: datamasterr/k8s-data-demo:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /app/story
            name: story-volume
      volumes:
        - name: story-volume
          hostPath:
            path: /data # pod의 볼륨이 워커노드에 있음 => pod가 달라도 상관x
            type: DirectoryOrCreate # 아무것도 없으면 빈 디렉터리 생성
    