apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
      - name: story
        image: datamasterr/k8s-data-demo:2
        env: # app.js에서 환경변수를 사용해서, .yaml에서만 유지보수 용이
        - name: STORY_FOLDER
          value: 'story'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /app/story
            name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim: # 영구볼륨과 연결고리
            claimName: host-pvc