### 단일 노드 환경 => hostPath 유형의 영구볼륨 ###
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem # or Block
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # 파드가 '동일 노드'에서 구동되는 경우에는 복수의 파드에서 볼륨에 접근할 수 있다. hostPath는 이것만 가능 
    #- ReadOnlyMany 볼륨이 '다수의 노드'에서 읽기 전용으로 마운트
    #- ReadWriteMany 볼륨이 '다수의 노드'에서 읽기-쓰기로 마운트
    #- ReadWriteOncePod 전체 클러스터에서 '단 하나의 파드'만 해당 PVC를 읽거나 쓸 수 있어야하는 경우
  hostPath:
    path: /data
    type: DirectoryOrCreate # 아무것도 없으면 빈 디렉터리 생성


