apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: task
  type: LoadBalancer # 외부에서 접근 가능
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: tasks-api
          image: datamasterr/kub-dep-tasks
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://hw:<db_password>@hello-eks.pagsh.mongodb.net/?retryWrites=true&w=majority&appName=Hello-EKS'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m' 
            requests:
              memory: '64Mi'
              cpu: '250m'