apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  selector: # Deployment가 감시해야할 pod레이블의 키-값 쌍을 정의
    # matchLabels:
    #  app: second-app
    #  tier: backend # tag느낌
    matchExpressions:
      - {key: app, operator: In, values: [second-app]} 
  replicas: 1 # pod을 scaling 개수
  template:
    metadata:
      labels:
        app: second-app
        tier: backend # tag느낌
    spec:
      containers: # -를 통해 pod 내 컨테이너를 구분
      - name: second-node
        image: datamasterr/k8s-first-app
        livenessProbe: # pod 모니터링 설정
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10 # 작업을 수행하는 빈도
          initialDelaySeconds: 5 # k8s가 처음으로 상태를 확인할 때까지의 시간
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # ports:
        #- containerPort: <Port>
      # - name: ...
      #  image: ...
